[workspace]
members = [
    "generator",
    "extract-generated-code-doc",
    "xcbgen-rs",
    "x11rb-protocol",
    "x11rb",
    "x11rb-async",
    "cairo-example",
    "xtrace-example",
    "xkbcommon-example",
]
