ignore:
  # Coverage for examples is not interesting, so exclude examples
  - "x11rb/examples"
  - "cairo-example"
  - "xtrace-example"

coverage:
  status:
    project:
      default:
        informational: true
